name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
          
  test-odfe-tarball:
    name: Run Tar Test
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: rishabh6788/odfe-test
          ref: master
          token: ${{ secrets.GitHub_PAT }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.x'
          java-package: jdk
          architecture: x64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run Tar
        run: |
          echo `pwd`
          #sudo add-apt-repository ppa:openjdk-r/ppa
          #sudo apt update -y
          #sudo apt install openjdk-11-jdk
          java -version
          
          cd elasticsearch/linux_distributions
          odfe_version=`../bin/version-info --od`
          echo $odfe_version
          cd $home
    
          #aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-$odfe_version.tar.gz .
          #ls -ltr
          #tar -zxf opendistroforelasticsearch-$odfe_version.tar.gz
          #cd opendistroforelasticsearch-$odfe_version
          #ls -ltr
          
          #nohup ./opendistro-tar-install.sh -Ecluster.name=odfe-cluster -Enode.name=odfe-node1 -Ehttp.host=0.0.0.0 -Ediscovery.type=single-node &
          
      - name: Run Curl Commands
        run: |
          cd /home/runner/work
          ls -ltr
          #echo "Sleeping"
          #sleep 1m
          #curl -XGET https://localhost:9200 -u admin:admin --insecure
          
     
        
