name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
          
  test-odfe-tarball:
    name: Run Tar Test
    runs-on: [macOS-10.14]
    steps:
      - uses: actions/checkout@v1
      - name: Run Tar
        run: |
          cd elasticsearch/linux_distributions
          odfe_version=`../bin/version-info --od`
          echo $odfe_version
          
          
     
        
