name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
          
  test-odfe-tarball:
    name: Run Tar Test
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run Tar
        run: |
          cd elasticsearch/linux_distributions
          odfe_version=`../bin/version-info --od`
          echo $odfe_version
          cd $home
    
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-$odfe_version.tar.gz .
          ls -ltr
          tar -zxf opendistroforelasticsearch-$odfe_version.tar.gz
          cd opendistroforelasticsearch-$odfe_version
          ls -ltr
          
          
     
        
