name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
  build:
    name: Create Docker Conrainer
    runs-on: [ubuntu-16.04]

    steps:
    - name: Run Debian Distribution
      run: |

        wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
        sudo apt-get install -y apt-transport-https
        echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a   /etc/apt/sources.list.d/opendistroforelasticsearch.list
        
        
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.1-amd64.deb
        sudo dpkg -i elasticsearch-oss-7.2.1-amd64.deb
        
        sudo apt-get update
        sudo /etc/init.d/elasticsearch start
        
        sudo netstat -natp
        
    - name: Run ES
      run: |
        
        sleep 10
        
        sudo cat /etc/elasticsearch/elasticsearch.yml
        
        curl -XGET https://127.0.0.1:9200 -u admin:admin --insecure
     
        
