name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
  Debian-Build-Test:
    name: Run and Test ODFE-Debian
    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
      with:
        repository: rishabh6788/odfe-test
        ref: master
        token: ${{ secrets.GitHub_PAT }}
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.5'
    - name: Run Debian Distribution
      run: |
        sudo sysctl -w vm.max_map_count=262144
        
        #sudo add-apt-repository -y ppa:openjdk-r/ppa
        #sudo apt update
        #sudo apt install -y openjdk-11-jdk
        
        #sudo sudo apt install -y net-tools

        #wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
        #echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a   /etc/apt/sources.list.d/opendistroforelasticsearch.list
        
        
        #wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.1-amd64.deb
        #sudo dpkg -i elasticsearch-oss-7.2.1-amd64.deb
        
        #sudo apt-get update
        #sudo apt install -y opendistroforelasticsearch
        #sudo /etc/init.d/elasticsearch start
        #sleep 30
        #sudo ls -ltr /var/log/elasticsearch/
        #sudo cat /var/log/elasticsearch/elasticsearch.log
        sudo netstat -natp
        
    - name: Run ES Tests
      run: |
        which python
        ls -ltr /usr/bin/python*
        cd ..
        cd odfe-test
        ls -ltr
        cd odfe-test
        sudo pip3 install virtualenv
        virtualenv --python=python3.7.5 runtime_env
        source runtime_env/bin/activate
        sudo pip3 install pytest
        sudo pip3 install requests
        pytest
   
  RPM-Build-Test:
    needs: [Debian-Build-Test]
    name: Run and Test RPM Distribution
    runs-on: [linux]
    steps:
      - uses: actions/checkout@v1
        with:
          repository: rishabh6788/odfe-test
          ref: master
          token: ${{ secrets.GitHub_PAT }}
      - name: Run RPM Distribution
        run: |
          sudo curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
          
          sudo yum install -y java-11-openjdk-devel
          sudo yum list opendistroforelasticsearch --showduplicates
          sudo yum install -y opendistroforelasticsearch-1.2.1
          sudo systemctl start elasticsearch.service
          
          sleep 25
          sudo cat /var/log/elasticsearch/elasticsearch.log
        
     
        
