name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
  build:
    name: Create Docker Conrainer
    runs-on: [ubuntu-latest]

    steps:
    - name: Run Debian Distribution
      run: |

        wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
        echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a   /etc/apt/sources.list.d/opendistroforelasticsearch.list
        
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.1-amd64.deb
        sudo dpkg -i elasticsearch-oss-7.2.1-amd64.deb
        
        sudo apt-get update
        sudo apt install -y opendistroforelasticsearch
        
    - name: Run ES
      run: |
        sudo systemctl start elasticsearch.service
        
        sleep 10
        
        systemctl status elasticsearch.service
        
    - name: Run Curl commands
      run: |
        
        
        curl -XGET https://localhost:9200 -u admin:admin --insecure
        
        curl -XGET https://localhost:9200/_cat/nodes?v -u admin:admin --insecure
        
        curl -XGET https://localhost:9200/_cat/plugins?v -u admin:admin --insecure
     
        
