name: CI

on:
  push:
    branches: 
      - sngri-actions-test
jobs:
  build:
    name: Create Docker Conrainer
    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
      with:
        repository: rishabh6788/odfe-test
        ref: master
        token: ${{ secrets.GitHub_PAT }}
    - name: Run Debian Distribution
      run: |
        sudo sysctl -w vm.max_map_count=262144
        
        #sudo add-apt-repository -y ppa:openjdk-r/ppa
        #sudo apt update
        #sudo apt install -y openjdk-11-jdk
        
        #sudo sudo apt install -y net-tools

        wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
        echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a   /etc/apt/sources.list.d/opendistroforelasticsearch.list
        
        
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.1-amd64.deb
        sudo dpkg -i elasticsearch-oss-7.2.1-amd64.deb
        
        sudo apt-get update
        sudo apt install -y opendistroforelasticsearch
        sudo /etc/init.d/elasticsearch start
        sleep 30
        #sudo ls -ltr /var/log/elasticsearch/
        #sudo cat /var/log/elasticsearch/elasticsearch.log
        sudo netstat -natp
        
    - name: Run Curl Commands
      run : |
        curl -XGET https://localhost:9200 -u admin:admin --insecure
        curl -XGET https://localhost:9200/_cat/nodes?v -u admin:admin --insecure
        curl -XGET https://localhost:9200/_cat/plugins?v -u admin:admin --insecure
        
    - name: Run ES Tests
      run: |
        sudo pip3 install pytest
        sudo pip3 install requests
        cd ..
        ls -ltr
        cd odfe-test
        ls -ltr
        cd odfe-test
        pytest
        
        
        
     
        
