name: CI

on:
  push:
    branches: 
      - git-actions
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: opendistro-for-elasticsearch/opendistro-infra
        ref: master
        token: ${{ secrets.GitHub_PAT }}    
    - name: Run Docker
      run: |
         nohup docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opendistroforelasticsearch/elasticsearch-test-ubuntu:1.3.0 &
    - name: Run ES
      run: |
        sleep 5m
        curl -XGET --insecure https://localhost:9200 -u admin:admin
        
        curl -X PUT "https://localhost:9200/test_index/_mappings" -u admin:admin --insecure -H 'Content-Type: application/json' -d'
        {
          "properties" : {
             "@timestamp" : {
                "type" : "date",
                "format" : "epoch_millis"
                },
             "test_field" : {
                "type" : "text"
                }
              }
            }'
          
        
